### ISSUE TITLE
Update Prisma to latest version

### ISSUE THREAD

**Issue by rafaell-lycan** [drizzle-team/drizzle-benchmarks#1]
Hey y'all 👋 

I want to suggest updating Prisma to its latest version to have a more fair comparison as they've solved some issues with latency and joins lately.

[Prisma's latest version: 5.7.1](https://github.com/prisma/prisma/releases/tag/5.7.1)

**Comment by sorenbs** [comment]
Take a look at this PR where I demonstrate that Prismas latest version performs roughly the same as Drizzle: https://github.com/drizzle-team/drizzle-benchmarks/pull/5

**Comment by AndriiSherman** [comment]
We've removed search queries from the results and upgraded to the latest version
